### ISSUE TITLE
Thanks for creating & curating but this is not an OPML?

### ISSUE THREAD

**Issue by tracure1337** [phretor/infosec-opml#1]
Thanks for creating & curating but this is not an OPML?

I fail to import it to Inoreader unfortunately.

Thanks so much for this!

**Comment by glaucusec** [comment]
> 

The `feeds.xml` file can be directly imported to inoreader from `OPML Import` section. Worked fine for me.

**Comment by phretor** [comment]
It's coming from a straight Inoreader export. I'm going to close this.

Please feel free to open again in case you have some specific error messages to report.

**Comment by carlaarchuleta308-source** [comment]
``[](url)

**Comment by carlaarchuleta308-source** [comment]
_/_
