### ISSUE TITLE
Personal blog

### ISSUE THREAD

**Issue by DiabloHorn** [phretor/infosec-opml#3]
Hi,

As discussed on Twitter, I'm opening this issues to check if you also allow personal blogs. It would concern this blog: https://diablohorn.com it's a low volume infosec blogs. However the subjects vary between technical, non-technical and a range of other infosec topics.

Thank you in advance,
DiabloHorn

**Comment by phretor** [comment]
Hi @DiabloHorn - I think this could go under "Infosec | Blogs"

Thanks for your contribution!

**Comment by phretor** [comment]
@DiabloHorn please go ahead and send a PR with the new resource + add yourself in the README along @glaucusec

**Comment by DiabloHorn** [comment]
Hi, apologies I was traveling. Will do, thank you!

**Comment by phretor** [comment]
Thank you.
